# Generated by Django 4.0.6 on 2022-12-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealclick',
            name='click_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата клика'),
        ),
    ]
